### ISSUE TITLE
guest client

### ISSUE THREAD

**Issue by Hen-Tar** [fa0311/twitter_openapi_python#13]
method "TwitterOpenapiPython().get_guest_client()" give error:

line 112, in get_twitter_openapi_python_client
    flag = http.request("GET", self.placeholder_url.format(hash=self.hash)).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTPResponse' object has no attribute 'json'

Process finished with exit code 1

**Comment by fa0311** [comment]
It's a bug, but a temporary solution is to upgrade urllib3.
It seems that urllib3 v2.0.0 or later is required.

**Comment by Hen-Tar** [comment]
Thanks, it fixed my problem.

**Comment by fa0311** [comment]
add support for urllib3 v1.x :)
