### ISSUE TITLE
can't get following list for an user

### ISSUE THREAD

**Issue by muratulashozturk** [fa0311/twitter_openapi_python#16]
Hello, I am trying to get the following list of a specific user, for example `yyy` account's `following` list(users), but I am always getting empty data(`{"data": {"user": {}}}`). I've matched the URL with the original one, then tried but it's still the same. What am I missing here exactly?

code:
```py
xScraper = TwitterOpenapiPython().get_client_from_cookies(cookies={"ct0": userCtZero, "auth_token": userAuthToken})
xUserApi = xScraper.get_user_api()
xUserListApi = xScraper.get_user_list_api()

userData = xUserApi.get_user_by_screen_name(specificAccount).data.user
userId = userData.id
userRestId = str(userData.rest_id)
userFollowingList = xUserListApi.get_following(user_id=userRestId, count=20)
```

**Comment by fa0311** [comment]
Which specificAccount is being referred to specifically?
elonmusk and faa0311 work fine.
